# Generated by Django 2.2.4 on 2021-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_services_app', '0002_auto_20210330_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=250),
        ),
    ]
