# Generated by Django 2.2.4 on 2021-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_services_app', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
    ]
